### PR TITLE
Updated v1.9.0

### PR DESCRIPTION
**Pull request by cmastalli**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

### CODE REVIEW

**Comment by jcarpent** [comment]
This is duplicates with  #15.

**Comment by cmastalli** [comment]
Sorry I didn't realise it. I will close this PR as the another one looks closer to be completed.

**Comment by cmastalli** [comment]
Sorry again, I reopened this PR as I noticed later the other one is closed.
Please let me know if we should or not close this PR as well.

**Comment by jcarpent** [comment]
I will close it and fix the two other open PRs.

**Pull request closed without merging**
